export enum Icons {
  AlertExclamation = 'icon-alert-exclamation',
  Basket = 'icon-basket',
  Chat = 'icon-chat',
  Close = 'icon-close',
  Edit = 'icon-edit',
  EyeClosed = 'icon-eye-closed',
  EyeOpen = 'icon-eye-open',
  Filter = 'icon-filter',
  Logo = 'icon-logo',
  Logout = 'icon-logout',
  Members = 'icon-members',
  Pen = 'icon-pen',
  PlusAdd = 'icon-plus-add',
  Profile = 'icon-profile',
  RemoveError = 'icon-remove-error',
  Success = 'icon-success',
}
